# Generated by Django 2.1.5 on 2019-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='external_id',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
